version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: develop
    commit-message:
      prefix: chore
      include: scope
    assignees:
      - pascaliske
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    target-branch: develop
    versioning-strategy: increase
    commit-message:
      prefix: chore
      include: scope
    assignees:
      - pascaliske
    labels:
      - dependencies
