language: node_js
node_js:
  - '9'
branches:
  only:
  - master
cache:
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build --progress false --base-href https://pascaliske.github.io/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
