language: node_js
node_js:
  - '9'
branches:
  only:
  - production
cache:
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build --progress false --base-href https://$PROD_DOMAIN
  - echo "# [$PROD_DOMAIN](https://$PROD_DOMAIN)\n" >> dist/README.md
  - echo "[![Build Status](https://travis-ci.com/pascaliske/pascaliske.github.io.svg?branch=production)](https://travis-ci.com/pascaliske/pascaliske.github.io)\n" >> dist/README.md
  - echo "This site was build automatically using Travis CI. Read more [here](https://$PROD_DOMAIN/deployment)." >> dist/README.md
deploy:
  provider: pages
  target-branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: $PROD_DOMAIN
  local_dir: dist
  on:
    branch: production
