language: node_js
node_js:
  - '9'
branches:
  only:
  - production
cache:
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build --progress false --base-href https://pascaliske.github.io/
  - echo "# [pascal-iske.de](https://pascal-iske.de)" >> README.md
  - echo "This site was build automatically using Travis CI. Read more [here](https://pascal-iske.de/deployment)." >> README.md
deploy:
  provider: pages
  target-branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: $PROD_DOMAIN
  local_dir: dist
  on:
    branch: production
