language: node_js
node_js:
  - '7'
  - '8'
  - '9'
before_install: yarn global add greenkeeper-lockfile@1
install:
  - yarn install
before_script: greenkeeper-lockfile-update
script:
  - yarn run lint
  - yarn run check
  - yarn run build --progress false --base-href https://$PROD_DOMAIN
after_script: greenkeeper-lockfile-upload
deploy:
  provider: firebase
  token:
    secure: xxPFmbu41iRKXilPyWD86CjtoBMk8bXRGlxNCtNNTIGSAqH2L39lgACcG2tweebnuVdKv0q3hpkjONuxPtIFzRJSc9OE1sszv3XR3MzVzWJhW0GiD+u1nqPVl1ZBbG+EcLumgWNH2CPRjb4xff9nDp/YK4GoVnnfVE+mQueAfY1cNgMdjnL+RGJazrnwhAwmMJe771B4DRtc4UknCmsxHWATdiAlcB34qifxXx51AV0KfnIB5dp6I8+Tb+nsjJ8iFM1ST7y1aNWBxJcZR8qrAl1AsO/gtytqyRqdN0jChfVw2ISiwxGCj7w+LrTsec7mT9gnfNAmgyHwTkSE0r7HRn/NAm29ZsGB31xSdyZQt8q3uhCAg4uP0W5NVlqzUOu2hJ3p7NuFeMp3heGe8XKbSx8fpl4nAdRRzVx4HoN3pOvS0E6WgDtiOeie593tx/6g7RLI4IBgYAMyCwzynsi9T1E5VkOzCgjX1E5X99e6Vy5qoqob+O9xWsSKEA0p7xnW6e8crABJDSd8zhkrKok5y07ly9RY59Rs53iB2011FdqV69zkGbOvss5qMK4Huf8v5S1TvyJCe6wAg+E/iOfsr2viX4XZPc4nE+R2CXwDIhmgUFFzKE3c4B0oxHE385ixN1nwSkHFxSE6AtYG8QIsrLiV67fsf9eOoeQUiCTG4QU=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 9
env:
  global:
    secure: QY+1MYVMPURyBBojv89X2CFMpXTIHPDaDgscT4D3ONm5pEeQLU1TNG9IQWcJzlCJb3xpwibROYCFo8cwwnSmGK0zapFRJaceAXtXwY6RwCtBpUw4AbPpI1zJb1ch+Gj3glHEH2T6TY0LbyGa5ZWdeW8Ppwo7u5X++W9F+kLcp+z+jAXvEeVynZ4aE9rgz+j7DdJrNzVGelCQNBGBlns4vyTdJxLfjSHzg58F5Yzrbn9PshtV9imMMkYdYVOTulTuNbEKDYltUKpASrT4Nz5eEV6k5l+VtqL6GCmB2pM0vUtI5Z6BciWBRePm0UiGpYUGqO+Wd3D+c95r5RP6j3W7sNIhYCItScGuQuUGlg219qJW9nSYZ6VISpX24v59PBr8wOyJEr14AlwtohFylm5gXiqYsthdHXOV7IEODanzcrht43gF7GGpQ8OZb5bw5bWL9euJ72BqEG+5CQAnGrM2L3yjVYjdOwSSqGK1uJvbv0t5+TZI3bAMFdHVG5oJFpj1nudgmBHgt715HVP1jTayPdd23S97tfd7Um8r6eKKFfh/0x7fFW4K2kvPzx8qr972uF5LpzuO1BGU82XDf0nm1AH8kNXvfFuOeniC05SEvpcSC4GgzfZWap3eOds7HNvPJXmKlJMBpdm+Hvgx70BN0oGKJlfRIqWm+H21c3Sybbs=
