language: node_js
node_js:
  - '8'
  - '9'
  - '10'
cache: yarn
before_install: yarn global add greenkeeper-lockfile@1
install:
  - yarn install
before_script: greenkeeper-lockfile-update
script:
  - yarn run lint
  - yarn run check
  - yarn run build --progress false --base-href https://$PROD_DOMAIN
after_script: greenkeeper-lockfile-upload
deploy:
  provider: firebase
  token:
    secure: xxPFmbu41iRKXilPyWD86CjtoBMk8bXRGlxNCtNNTIGSAqH2L39lgACcG2tweebnuVdKv0q3hpkjONuxPtIFzRJSc9OE1sszv3XR3MzVzWJhW0GiD+u1nqPVl1ZBbG+EcLumgWNH2CPRjb4xff9nDp/YK4GoVnnfVE+mQueAfY1cNgMdjnL+RGJazrnwhAwmMJe771B4DRtc4UknCmsxHWATdiAlcB34qifxXx51AV0KfnIB5dp6I8+Tb+nsjJ8iFM1ST7y1aNWBxJcZR8qrAl1AsO/gtytqyRqdN0jChfVw2ISiwxGCj7w+LrTsec7mT9gnfNAmgyHwTkSE0r7HRn/NAm29ZsGB31xSdyZQt8q3uhCAg4uP0W5NVlqzUOu2hJ3p7NuFeMp3heGe8XKbSx8fpl4nAdRRzVx4HoN3pOvS0E6WgDtiOeie593tx/6g7RLI4IBgYAMyCwzynsi9T1E5VkOzCgjX1E5X99e6Vy5qoqob+O9xWsSKEA0p7xnW6e8crABJDSd8zhkrKok5y07ly9RY59Rs53iB2011FdqV69zkGbOvss5qMK4Huf8v5S1TvyJCe6wAg+E/iOfsr2viX4XZPc4nE+R2CXwDIhmgUFFzKE3c4B0oxHE385ixN1nwSkHFxSE6AtYG8QIsrLiV67fsf9eOoeQUiCTG4QU=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 10
env:
  global:
    - secure: QY+1MYVMPURyBBojv89X2CFMpXTIHPDaDgscT4D3ONm5pEeQLU1TNG9IQWcJzlCJb3xpwibROYCFo8cwwnSmGK0zapFRJaceAXtXwY6RwCtBpUw4AbPpI1zJb1ch+Gj3glHEH2T6TY0LbyGa5ZWdeW8Ppwo7u5X++W9F+kLcp+z+jAXvEeVynZ4aE9rgz+j7DdJrNzVGelCQNBGBlns4vyTdJxLfjSHzg58F5Yzrbn9PshtV9imMMkYdYVOTulTuNbEKDYltUKpASrT4Nz5eEV6k5l+VtqL6GCmB2pM0vUtI5Z6BciWBRePm0UiGpYUGqO+Wd3D+c95r5RP6j3W7sNIhYCItScGuQuUGlg219qJW9nSYZ6VISpX24v59PBr8wOyJEr14AlwtohFylm5gXiqYsthdHXOV7IEODanzcrht43gF7GGpQ8OZb5bw5bWL9euJ72BqEG+5CQAnGrM2L3yjVYjdOwSSqGK1uJvbv0t5+TZI3bAMFdHVG5oJFpj1nudgmBHgt715HVP1jTayPdd23S97tfd7Um8r6eKKFfh/0x7fFW4K2kvPzx8qr972uF5LpzuO1BGU82XDf0nm1AH8kNXvfFuOeniC05SEvpcSC4GgzfZWap3eOds7HNvPJXmKlJMBpdm+Hvgx70BN0oGKJlfRIqWm+H21c3Sybbs=
    - secure: FVK0wexU71vn/EGT7SBABuTFheiPMEAxa4KOW/qG/1NQVmkV5NMYRGbvuPJ17G1222St9AksPfSQoMEJKF/N7Wc4dhAJbKdXV3c7RAHHZbQlkhcAGIwfbcmjloj+RKOFjgMEHSR7peKF5qgwFKNXD8xWeF6f9AFAdmwYk/KLK9bCiiY7CdzBt6VQfX6kIRJRfi4Lqd0KXgR4inYgeU1kBd/vM+N/T/4uHtn0p4N5fZ2C0W6cO8EEtdjh0XRYfPFliGNUGo09JmoyarxqZruj3N9L/xkF49798hUtvWJQRrZjFo72In111UAWlxUsD+7Fo29wYUbUM/Ip2rkIBJBgwaODMTgToSnsNbk9c1YZXAjxBnFsHUx+Si91btLNd4Tc7cR3QoTlxXEizHcEbH68IPd8FQl5JSuoQd+tHIe44GRtHZ3fj1pRBQvuZWwd1GzRRY1wBSOWkZvtib1AI0TAN2h4SGl6gRIFhDAT76o/nX6eo/OXcAD7RdJDpijgNT5MWUqz2mV4kYlC5D+N0alq5g8APdwt/y5nhOmt1hO7AAhqPf1q3nQZrjGRoLAA9iGgwTKkwSDQTZ2fme/Py8c9D9E1J/1riXQEUNH5Col2YZAPSXT3sZQ+OTmS47t/e1RzM/oxDch1zF6e+eAGGKletZycCHvadBwL92pFDre/PNg=
