name: Deploy site
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v2

      # prepare
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile

      # test
      - run: yarn run lint
      - run: yarn run e2e

      # build
      - run: yarn run build:app --progress false --base-href https://${{ secrets.PROD_DOMAIN }}
      - run: yarn run build:server --progress false
      - run: yarn run build:cfn
      - run: yarn run build:prerender
      - run: yarn run bundlewatch

      # deploy
      # - run: yarn run lighthouse --output-path=./report.html https://${{ secrets.PROD_DOMAIN }}
      # - run: yarn run now report.html --token ${{ secrets.NOW_TOKEN }} --no-clipboard --public
      # - run: yarn run sentry-cli releases new "$TRAVIS_TAG"
      # - run: yarn run sentry-cli releases set-commits --auto "$TRAVIS_TAG"
      # - run: yarn run sentry-cli releases files "$TRAVIS_TAG" upload-sourcemaps ./dist --no-rewrite
      # - run: yarn run sentry-cli releases deploys "$TRAVIS_TAG" new -e production
      # - run: yarn run sentry-cli releases finalize "$TRAVIS_TAG"
