name: Deploy App
on: pull_request

jobs:
  preview:
    name: Preview
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      # prepare
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile

      # test
      - run: yarn run lint

      # build
      - run: yarn run build:app --progress false --base-href https://${{ secrets.PROD_DOMAIN }}
      - run: yarn run build:server --progress false
      - run: yarn run build:cfn
      - run: yarn run build:prerender
      - run: yarn run bundlewatch

      # deploy
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          projectId: pascaliske-dev
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PASCALISKE_DEV }}'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
