name: Deploy App
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Production
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      # prepare
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile

      # test
      - run: yarn run lint
      - uses: cypress-io/github-action@v2
        with:
          command: yarn run e2e --headless --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore

      # build
      - run: yarn run build:app --progress false --base-href https://${{ secrets.PROD_DOMAIN }}
      - run: yarn run build:server --progress false
      - run: yarn run build:cfn
      - run: yarn run build:prerender
      - run: yarn run bundlewatch

      # deploy
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          projectId: pascaliske-dev
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PASCALISKE_DEV }}'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          channelId: live

      # - run: yarn run lighthouse --output-path=./report.html https://${{ secrets.PROD_DOMAIN }}
      # - run: yarn run now report.html --token ${{ secrets.NOW_TOKEN }} --no-clipboard --public
      # - run: yarn run sentry-cli releases new "$TRAVIS_TAG"
      # - run: yarn run sentry-cli releases set-commits --auto "$TRAVIS_TAG"
      # - run: yarn run sentry-cli releases files "$TRAVIS_TAG" upload-sourcemaps ./dist --no-rewrite
      # - run: yarn run sentry-cli releases deploys "$TRAVIS_TAG" new -e production
      # - run: yarn run sentry-cli releases finalize "$TRAVIS_TAG"
