name: Test site
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v2

      # prepare
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile

      # test
      - run: yarn run lint
      - run: yarn run build:app --progress false --base-href https://${{ secrets.PROD_DOMAIN }}
      - run: yarn run build:server --progress false
      - run: yarn run build:cfn
      - run: yarn run build:prerender
      - run: yarn run bundlewatch
      - run: yarn run e2e
